Add TLSH, SHA1 column at report
fosslight/fosslight_yocto_scanner pull request #23
Opened 2024-03-26 12:39 UTC by bjk7119

## Description

- Add TLSH, SHA1 column at report
    - These columns will be hidden by dafault
## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Documentation update
- [ ] Refactoring, Maintenance
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

2024-04-02 23:24 UTC, soimkim requested changes

2024-04-02 23:24 UTC, soimkim commented on requirements.txt
> +fosslight_util>=1.4.38
1.4.39 아닌지요?

2024-04-02 23:24 UTC, soimkim commented on src/fosslight_yocto/_package_item.py
> +_TLSH_CHECKSUM_NULL = "0"
_는 private 변수에 붙입니다.
이 변수는 그냥 상수이므로 맨 앞에 _ 제거 제안드립니다.

2024-04-03 01:32 UTC, bjk7119 commented on requirements.txt
> +fosslight_util>=1.4.38
그새 바뀌었네요 1.4.39가 맞습니다. 수정완료

2024-04-03 09:00 UTC, soimkim requested changes
src/fosslight_yocto/_package_item.py의  row = [file, self.name, self.version, ','.join(license_to_print), self.download_location,
                           self.homepage, self.copyright, exclude, self.comment]도 수정 필요합니다.

2024-04-04 08:48 UTC, soimkim approved these changes

2024-04-08 04:29 UTC, merged