updating archiving source codes with -e option
fosslight/fosslight_yocto_scanner pull request #45
Opened 2024-12-04 08:02 UTC by heedu

## Description

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation update
- [ ] Refactoring, Maintenance
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

2024-12-04 08:03 UTC, heedu commented
needs to get review.

2025-01-09 00:35 UTC, soimkim commented
@heedu , 수정한 내용이 무엇인지 Description 에 작성 부탁드립니다.

2025-01-09 02:24 UTC, heedu commented
@soimkim 
update 완료하였습니다.

2025-01-09 02:37 UTC, soimkim requested changes

2025-01-09 02:37 UTC, soimkim commented on src/fosslight_yocto/create_oss_report_for_yocto.py
> +        oss_item['source_done'] = item['complete']
'complete'  키 있는지 체크해주세요.

2025-01-09 02:37 UTC, soimkim commented on src/fosslight_yocto/_package_item.py
>          self.pr = ""
추가된 변수는 하위로 이동해주시고 e옵션용 변수로 주석 달고, 각각에 대한 설명을 변수 옆 주석으로도 추가해주십시오.

2025-01-09 02:37 UTC, soimkim commented
@heedu , build 에러 확인 부탁드리며,
bom.bbclass 수정 대신 bom_e_option.bbclass와 같이 분리하여주십시오.

2025-01-09 02:42 UTC, soimkim commented
-e 옵션으로 소스 압축시, output 결과물도 포함되어서 이를 제외시키고자 build time 시간 이후에 생성된 파일은 취합하지 않는 변경사항으로 확인합니다.

2025-01-09 04:50 UTC, closed without merging